config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  # patch 'tasks/mark/:id', to: 'tasks#mark_as_complete', as: :mark_task_as_complete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_id, only: [:show, :edit, :update, :destroy, :mark_as_complete]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    new_task = Task.new(task_params)
    redirect_to tasks_path if new_task.save
  end

  def edit
  end

  def show
  end

  # def mark_as_complete
  #   @task.complete = true
  #   @task.save
  #   redirect_to tasks_path
  # end

  def update
    @task.update(task_params)
    redirect_to task_path(@task.id)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:name, :details, :complete)
  end

  def find_id
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name, placeholder: "dsadsa" %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="container">
  <div class="container-info">
    <h1> All my tasks </h1>
    <div class="content">
      <% @tasks.each do |task| %>
        <h3><%= link_to task.name, task_path(task) %> <%= task.complete ? '[X]' : '[ ]' %> </h3>
      <% end %>
    </div>

    <%= link_to "Create new task", new_task_path, class: "button button-primary" %>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
<div class="container">
  <h1> <%= @task.name %> </h1>

  <h3> <%= @task.details %> </h3>


  <%= link_to "Edit you task", edit_task_path(@task), class: "button" %>


  <%= link_to "Destroy task", task_path(@task), method: :delete, class: "button", data: { confirm: "Are you sure"}  %>

  <% if !@task.complete %>
    <%= link_to task_path(@task, task: {complete: true} ), method: :patch, class: "button" do %>
      <i class="fa fa-times"></i>
    <% end %>
  <% else %>
    <%= link_to task_path(@task, task: {complete: false} ), method: :patch, class: "button" do %>
      <i class="fa fa-check"></i>
    <% end %>
  <% end %>

<!--   <%# link_to 'Mark', mark_task_as_complete_path(@task), method: :patch %> -->
</div>